# Generated by Django 5.0 on 2024-01-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='active_field',
            new_name='active',
        ),
    ]
